In [1]:
import cv2
import numpy as np
from skimage import io,img_as_float
from skimage.color import rgb2gray
from scipy.stats import kurtosis,skew,entropy
import os
import pandas as pd
import scipy
import matplotlib.pyplot as plt
import seaborn as sns
from skimage.feature import hog

In [2]:
train='C:/Users/HP/dataset_train/Train_set'
test='C:/Users/HP/dataset_test/Test_data'

In [3]:
def feature_extraction(dir):
    df=pd.DataFrame()
    for cls in os.listdir(dir):
        print(cls)
        for image in os.listdir(os.path.join(dir,cls)):
            read_img=cv2.imread(os.path.join(dir,cls,image),cv2.IMREAD_GRAYSCALE)/255

            df=df.append({
                "Class":cls,
                "Image_path":os.path.join(dir,cls,image),
                "Mean":np.mean(read_img),
                "Median":np.median(read_img),
                "Std":np.std(read_img),
                "Kurtosis":kurtosis(read_img,axis=None),
                "Skew":skew(read_img,axis=None),
                "Entropy":entropy(read_img,axis=None),
                
            },ignore_index=True)
    return df

In [4]:
df_train=feature_extraction(train)
df_test=feature_extraction(test)

0Normal
1Doubtful
2Mild
3Moderate
4Severe
0Normal
1Doubtful
2Mild
3Moderate
4Severe

In [5]:
df_train

,Class,Entropy,Image_path,Kurtosis,Mean,Median,Skew,Std
0,0Normal,10.898499,C:/Users/HP/dataset_train/Train_set\0Normal\hi...,-1.210018,0.505427,0.517647,-0.013360,0.290548
1,0Normal,10.883239,C:/Users/HP/dataset_train/Train_set\0Normal\hi...,-1.225519,0.497272,0.494118,-0.001496,0.295484
2,0Normal,10.876116,C:/Users/HP/dataset_train/Train_set\0Normal\hi...,-1.231840,0.492410,0.486275,0.005931,0.296789
3,0Normal,10.887820,C:/Users/HP/dataset_train/Train_set\0Normal\hi...,-1.227225,0.499669,0.501961,-0.007063,0.294136
4,0Normal,10.899954,C:/Users/HP/dataset_train/Train_set\0Normal\hi...,-1.211176,0.504940,0.509804,-0.010695,0.289511
...,...,...,...,...,...,...,...,...
1440,4Severe,10.892874,C:/Users/HP/dataset_train/Train_set\4Severe\hi...,-1.223269,0.502017,0.509804,-0.010444,0.292307
1441,4Severe,10.833878,C:/Users/HP/dataset_train/Train_set\4Severe\hi...,-1.246984,0.472813,0.474510,0.015287,0.306061
1442,4Severe,10.906268,C:/Users/HP/dataset_train/Train_set\4Severe\hi...,-1.246750,0.506835,0.517647,0.002725,0.288402
1443,4Severe,10.877526,C:/Users/HP/dataset_train/Train_set\4Severe\hi...,-1.213209,0.493469,0.494118,-0.010605,0.295495
1444,4Severe,10.898368,C:/Users/HP/dataset_train/Train_set\4Severe\hi...,-1.212569,0.503958,0.505882,-0.012316,0.289911

In [6]:
df_train.to_csv("train_OA_processed.csv",index=False)

In [7]:
train_features=df_train.loc[:, ~df_train.columns.isin(['Class', 'Image_path'])]

In [8]:
train_classes=df_train['Class'].to_numpy()

In [9]:
train_features

        Entropy  Kurtosis      Mean    Median      Skew       Std
0     10.898499 -1.210018  0.505427  0.517647 -0.013360  0.290548
1     10.883239 -1.225519  0.497272  0.494118 -0.001496  0.295484
2     10.876116 -1.231840  0.492410  0.486275  0.005931  0.296789
3     10.887820 -1.227225  0.499669  0.501961 -0.007063  0.294136
4     10.899954 -1.211176  0.504940  0.509804 -0.010695  0.289511
...         ...       ...       ...       ...       ...       ...
1440  10.892874 -1.223269  0.502017  0.509804 -0.010444  0.292307
1441  10.833878 -1.246984  0.472813  0.474510  0.015287  0.306061
1442  10.906268 -1.246750  0.506835  0.517647  0.002725  0.288402
1443  10.877526 -1.213209  0.493469  0.494118 -0.010605  0.295495
1444  10.898368 -1.212569  0.503958  0.505882 -0.012316  0.289911

[1445 rows x 6 columns]

In [10]:
from sklearn.preprocessing import StandardScaler
scaled_features = StandardScaler().fit_transform(train_features.values)
train_scaled_features_df = pd.DataFrame(scaled_features, index=train_features.index, columns=train_features.columns)

In [11]:
train_scaled_features_df

       Entropy  Kurtosis      Mean    Median      Skew       Std
0     0.821189  0.609794  0.885379  0.987627 -0.855213 -0.742855
1     0.710479  0.388726  0.745551  0.704351 -0.785483 -0.522381
2     0.658803  0.298573  0.662177  0.609926 -0.741838 -0.464082
3     0.743714  0.364396  0.786651  0.798777 -0.818205 -0.582589
4     0.831739  0.593278  0.877029  0.893202 -0.839547 -0.789179
...        ...       ...       ...       ...       ...       ...
1440  0.780375  0.420816  0.826920  0.893202 -0.838072 -0.664296
1441  0.352375  0.082596  0.326122  0.468288 -0.686848 -0.049935
1442  0.877547  0.085935  0.909538  0.987627 -0.760678 -0.838719
1443  0.669031  0.564285  0.680324  0.704351 -0.839021 -0.521890
1444  0.820233  0.573412  0.860188  0.845989 -0.849075 -0.771313

[1445 rows x 6 columns]

In [12]:
train_classes

array(['0Normal', '0Normal', '0Normal', ..., '4Severe', '4Severe',
       '4Severe'], dtype=object)

In [13]:
df_test

,Class,Entropy,Image_path,Kurtosis,Mean,Median,Skew,Std
0,0Normal,10.898499,C:/Users/HP/dataset_test/Test_data\0Normal\Nor...,-1.210018,0.505427,0.517647,-0.013360,0.290548
1,0Normal,10.883239,C:/Users/HP/dataset_test/Test_data\0Normal\Nor...,-1.225519,0.497272,0.494118,-0.001496,0.295484
2,0Normal,10.716094,C:/Users/HP/dataset_test/Test_data\0Normal\Nor...,-1.315066,0.418052,0.396078,0.184510,0.324295
3,0Normal,10.865681,C:/Users/HP/dataset_test/Test_data\0Normal\Nor...,-1.240680,0.488977,0.486275,0.004530,0.300265
4,0Normal,10.822920,C:/Users/HP/dataset_test/Test_data\0Normal\Nor...,-1.260517,0.466747,0.458824,0.037754,0.308532
...,...,...,...,...,...,...,...,...
437,4Severe,10.908901,C:/Users/HP/dataset_test/Test_data\4Severe\Sev...,-1.232259,0.507259,0.505882,0.018523,0.286438
438,4Severe,10.654533,C:/Users/HP/dataset_test/Test_data\4Severe\Sev...,-1.324382,0.394899,0.360784,0.251412,0.330112
439,4Severe,10.917006,C:/Users/HP/dataset_test/Test_data\4Severe\Sev...,-1.263747,0.506671,0.501961,0.055248,0.283361
440,4Severe,10.903189,C:/Users/HP/dataset_test/Test_data\4Severe\Sev...,-1.225100,0.504353,0.501961,0.007408,0.288252
441,4Severe,10.605169,C:/Users/HP/dataset_test/Test_data\4Severe\Sev...,-1.308606,0.375702,0.329412,0.325537,0.332872

In [14]:
df_test.to_csv("test_OA_processed.csv",index=False)

In [15]:
test_features=df_test.loc[:, ~df_test.columns.isin(['Class', 'Image_path'])]

In [16]:
test_classes=df_test['Class'].to_numpy()

In [17]:
test_features

       Entropy  Kurtosis      Mean    Median      Skew       Std
0    10.898499 -1.210018  0.505427  0.517647 -0.013360  0.290548
1    10.883239 -1.225519  0.497272  0.494118 -0.001496  0.295484
2    10.716094 -1.315066  0.418052  0.396078  0.184510  0.324295
3    10.865681 -1.240680  0.488977  0.486275  0.004530  0.300265
4    10.822920 -1.260517  0.466747  0.458824  0.037754  0.308532
..         ...       ...       ...       ...       ...       ...
437  10.908901 -1.232259  0.507259  0.505882  0.018523  0.286438
438  10.654533 -1.324382  0.394899  0.360784  0.251412  0.330112
439  10.917006 -1.263747  0.506671  0.501961  0.055248  0.283361
440  10.903189 -1.225100  0.504353  0.501961  0.007408  0.288252
441  10.605169 -1.308606  0.375702  0.329412  0.325537  0.332872

[442 rows x 6 columns]

In [18]:
test_classes

array(['0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '0Normal', '0Normal', '0Normal', '0Normal',
       '0Normal', '0Normal', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful', '1Doubtful',
       '1Doubtful', '1Doubtful', '1Doubtful', '2Mild', '2Mild', '2Mild',
       '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild',
       '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild',
       '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild',
       '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild',
       '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild',
       '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild', '2Mild',
       '3Moderate', '3Moderate', '3Moderate', '3Moderate', '3Moderate',
       '3Moderate', '3Moderate', '3Moderate', '3Moderate', '3Moderate',
       '3Moderate', '3Moderate', '3Moderate', '3Moderate', '3Moderate',
       '3Moderate', '3Moderate', '3Moderate', '3Moderate', '3Moderate',
       '3Moderate', '3Moderate', '3Moderate', '3Moderate', '3Moderate',
       '3Moderate', '3Moderate', '3Moderate', '3Moderate', '3Moderate',
       '3Moderate', '3Moderate', '3Moderate', '3Moderate', '3Moderate',
       '3Moderate', '3Moderate', '3Moderate', '3Moderate', '3Moderate',
       '3Moderate', '3Moderate', '3Moderate', '3Moderate', '4Severe',
       '4Severe', '4Severe', '4Severe', '4Severe', '4Severe', '4Severe',
       '4Severe', '4Severe', '4Severe', '4Severe', '4Severe', '4Severe',
       '4Severe', '4Severe', '4Severe', '4Severe', '4Severe', '4Severe',
       '4Severe', '4Severe', '4Severe', '4Severe', '4Severe', '4Severe',
       '4Severe', '4Severe', '4Severe', '4Severe', '4Severe', '4Severe',
       '4Severe', '4Severe', '4Severe', '4Severe', '4Severe', '4Severe',
       '4Severe', '4Severe', '4Severe', '4Severe', '4Severe', '4Severe',
       '4Severe', '4Severe', '4Severe', '4Severe', '4Severe'],
      dtype=object)

In [19]:
scaled_features = StandardScaler().fit_transform(test_features.values)
test_scaled_features_df = pd.DataFrame(scaled_features, index=test_features.index, columns=test_features.columns)

In [20]:
test_scaled_features_df

      Entropy  Kurtosis      Mean    Median      Skew       Std
0    0.646521  0.388118  0.694643  0.792300 -0.658335 -0.597350
1    0.531999  0.184895  0.549298  0.506055 -0.588193 -0.361925
2   -0.722357 -0.989132 -0.862760 -0.686631  0.511453  1.012277
3    0.400234 -0.013874  0.401442  0.410640 -0.552568 -0.133879
4    0.079325 -0.273950  0.005201  0.076688 -0.356156  0.260421
..        ...       ...       ...       ...       ...       ...
437  0.724579  0.096526  0.727304  0.649178 -0.469845 -0.793394
438 -1.184354 -1.111270 -1.275448 -1.115999  0.906973  1.289694
439  0.785405 -0.316309  0.716827  0.601470 -0.252729 -0.940137
440  0.681717  0.190381  0.675514  0.601470 -0.535555 -0.706885
441 -1.554806 -0.904433 -1.617621 -1.497658  1.345191  1.421321

[442 rows x 6 columns]

In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

classification_models = [
    KNeighborsClassifier(5),#(3),
    SVC(kernel='linear'),#, C=0.025),
    SVC(kernel='rbf'),
    DecisionTreeClassifier(),#max_depth=5),
    RandomForestClassifier(),#max_depth=5, n_estimators=10, max_features=1),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis()]

scores = []
for model in classification_models:
    model.fit(train_scaled_features_df, train_classes)
    score = model.score(test_scaled_features_df, test_classes)
    model_name = type(model).__name__
    if model_name=='SVC' and model.kernel=='rbf': model_name+=' RBF kernel'
    scores.append((model_name,(f'{100*score:.2f}%')))
# Make it pretty
scores_df = pd.DataFrame(scores,columns=['Classifier','Accuracy Score'])
scores_df.sort_values(by='Accuracy Score',axis=0,ascending=False)

                      Classifier Accuracy Score
7  QuadraticDiscriminantAnalysis         45.48%
5             AdaBoostClassifier         42.31%
2                 SVC RBF kernel         38.46%
1                            SVC         38.24%
0           KNeighborsClassifier         37.10%
4         RandomForestClassifier         36.20%
6                     GaussianNB         31.67%
3         DecisionTreeClassifier         26.70%

In [22]:
from sklearn.neural_network import MLPClassifier

# Default 'off-the-shelf' MLP from sklearn
model = MLPClassifier(
    random_state = 69
)

# #################### unscaled features #####################
# X_train, X_test, y_train, y_test = train_test_split(
#     features, 
#     emotions, 
#     test_size=0.2, 
#     random_state=69
# )
  
model.fit(train_scaled_features_df, train_classes)

print(f'Possible emotions predicted by model:{model.classes_}')
print(f'Unscaled MLP Model\'s accuracy on training set is {100*model.score(train_scaled_features_df, train_classes):.2f}%')
print(f'Unscaled MLP Model\'s accuracy on test set is {100*model.score(test_scaled_features_df, test_classes):.2f}%')

Possible emotions predicted by model:['0Normal' '1Doubtful' '2Mild' '3Moderate' '4Severe']
Unscaled MLP Model's accuracy on training set is 43.04%
Unscaled MLP Model's accuracy on test set is 35.52%

C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(